---

clusterName: "fivex"
imageTag: "5.6.15"
esMajorVersion: 5

extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-fivex-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-fivex-credentials
        key: username
