kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
 name: px-db-rf1-es-data-sc
provisioner: kubernetes.io/portworx-volume
allowVolumeExpansion: true
parameters:
 repl: "1"
 priority_io: "high"
 io_profile: "db"
 disable_io_profile_protection: "1"
 group: "esdata"
 fg: "true"
