---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
 name: px-db-rf2-sc-db-remote
provisioner: kubernetes.io/portworx-volume
allowVolumeExpansion: true
parameters:
 repl: "2"
 priority_io: "high"
 io_profile: "db_remote"
 disable_io_profile_protection: "1"
