kind: Service
apiVersion: v1
metadata:
  name: datastore-kibana-ext-lb
  labels: 
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: 10000
    targetPort: 5601
  type: LoadBalancer
