---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeepercli-aci
spec:
  selector:
    matchLabels:
      app: zookeepercli-aci
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeepercli-aci
    spec:
      containers:
      - name: zookeepercli-aci
        image: david62243/zookeepercli:v0.1
        command:
           - sh
           - -c
           - "exec tail -f /dev/null"
        imagePullPolicy: Always
      nodeSelector:
        kubernetes.io/role: agent
        beta.kubernetes.io/os: linux
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Exists
      - key: azure.com/aci
        effect: NoSchedule
