---
apiVersion: v1
kind: Service
metadata:
  name: es
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 9200
  selector:
    app: datastore-elasticsearch-client
