---
apiVersion: v1
kind: Service
metadata:
  name: rttest-eim-mon
  labels:
    app: rttest-eim-mon
spec:
  ports:
  clusterIP: None
  selector:
    app: rttest-eim-mon
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rttest-eim-mon
spec:
  serviceName: rttest-eim-mon
  selector:
    matchLabels:
      app: rttest-eim-mon
  replicas: 1
  template:
    metadata:
      labels:
        app: rttest-eim-mon
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - agent
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: rttest-mon
        image: david62243/rttest-mon:20190718
        command: ["/bin/bash", "-c"]
        args:
          - >-
            cd /opt/rttest;
            java -cp target/rttest.jar com.esri.rttest.mon.ElasticIndexMon http://datastore-elasticsearch-client-headless:9200/planes 20 4 
        imagePullPolicy: Always
      tolerations:
      - key: "key"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        func: test
