apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-exp
parameters:
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
allowVolumeExpansion: true